/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border) / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        foreground: "hsl(var(--foreground) / <alpha-value>)",
        card: "hsl(var(--card) / <alpha-value>)",
        "card-foreground": "hsl(var(--card-foreground) / <alpha-value>)",
        surface: "hsl(var(--surface) / <alpha-value>)",
        muted: "hsl(var(--muted) / <alpha-value>)",
        "muted-foreground": "hsl(var(--muted-foreground) / <alpha-value>)",
        input: "hsl(var(--input) / <alpha-value>)",
        primary: "hsl(var(--primary) / <alpha-value>)",
        "primary-foreground": "hsl(var(--primary-foreground) / <alpha-value>)",
        action: "hsl(var(--action) / <alpha-value>)",
        "action-foreground": "hsl(var(--action-foreground) / <alpha-value>)",
        focus: "hsl(var(--focus) / <alpha-value>)",
        success: "hsl(var(--success) / <alpha-value>)",
        "success-muted": "hsl(var(--success-muted) / <alpha-value>)",
        "success-border": "hsl(var(--success-border) / <alpha-value>)",
        "success-foreground": "hsl(var(--success-foreground) / <alpha-value>)",
        warning: "hsl(var(--warning) / <alpha-value>)",
        "warning-muted": "hsl(var(--warning-muted) / <alpha-value>)",
        "warning-border": "hsl(var(--warning-border) / <alpha-value>)",
        "warning-foreground": "hsl(var(--warning-foreground) / <alpha-value>)",
        danger: "hsl(var(--danger) / <alpha-value>)",
        "danger-muted": "hsl(var(--danger-muted) / <alpha-value>)",
        "danger-border": "hsl(var(--danger-border) / <alpha-value>)",
        "danger-foreground": "hsl(var(--danger-foreground) / <alpha-value>)",
        info: "hsl(var(--info) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "Inter", "system-ui", "sans-serif"],
        mono: ["var(--font-mono)", "ui-monospace", "monospace"],
      },
      borderRadius: {
        sm: "4px",
        md: "var(--radius-default)",
        lg: "var(--radius-default)",
        xl: "8px",
      },
      boxShadow: {
        card: "rgba(0, 0, 0, 0.4) 0px 2px 4px 0px",
        inset: "rgb(35, 37, 42) 0px 0px 0px 1px inset",
      },
    },
  },
  plugins: [],
};
