PROMPT_VERSION_NAMESPACE = "thesys"

STRUCTURED_OUTPUT_SMOKE_TEST_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-output-smoke-test:v1"
)
STRUCTURED_INTAKE_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:structured-intake:v1"
STRUCTURED_INTAKE_FINALIZE_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-intake-finalize:v1"
)
EVIDENCE_INGESTION_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:evidence-ingestion:v1"
EVIDENCE_RETRIEVAL_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:evidence-retrieval:v1"
OPPORTUNITY_BRIEF_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:opportunity-brief:v1"
COMPETITOR_ANALYSIS_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:competitor-analysis:v1"
ASSUMPTION_EXTRACTION_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:assumption-extraction:v1"
VALIDATION_PLAN_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:validation-plan:v1"
RESEARCH_SPRINT_PLANNING_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:research-sprint-planning:v1"
)
