PROMPT_VERSION_NAMESPACE = "thesys"

STRUCTURED_OUTPUT_SMOKE_TEST_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-output-smoke-test:v1"
)
STRUCTURED_INTAKE_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:structured-intake:v1"
STRUCTURED_INTAKE_FINALIZE_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-intake-finalize:v1"
)
EVIDENCE_INGESTION_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:evidence-ingestion:v1"
EVIDENCE_RETRIEVAL_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:evidence-retrieval:v1"
OPPORTUNITY_BRIEF_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:opportunity-brief:v1"
