PROMPT_VERSION_NAMESPACE = "thesys"

STRUCTURED_OUTPUT_SMOKE_TEST_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-output-smoke-test:v1"
)
STRUCTURED_INTAKE_PROMPT_VERSION = f"{PROMPT_VERSION_NAMESPACE}:structured-intake:v1"
STRUCTURED_INTAKE_FINALIZE_PROMPT_VERSION = (
    f"{PROMPT_VERSION_NAMESPACE}:structured-intake-finalize:v1"
)
