import json
from collections.abc import Sequence
from dataclasses import dataclass
from decimal import Decimal
from types import UnionType
from typing import Any, Literal, TypeVar, Union, get_args, get_origin

from pydantic import BaseModel, ValidationError

from app.ai.litellm_client import ChatMessage, LiteLLMClient, LLMCompletion
from app.core.config import Settings

StructuredModel = TypeVar("StructuredModel", bound=BaseModel)


@dataclass(frozen=True)
class StructuredOutputResult:
    parsed: BaseModel
    completion: LLMCompletion


class StructuredOutputError(RuntimeError):
    pass


def generate_structured_output(
    settings: Settings,
    output_schema: type[StructuredModel],
    messages: Sequence[ChatMessage],
    *,
    model: str | None = None,
    temperature: float = 0.0,
) -> StructuredOutputResult:
    if settings.should_use_llm_stub:
        return _stub_structured_output(output_schema, messages, model or settings.litellm_model)

    schema_instruction = ChatMessage(
        role="system",
        content=(
            "Return only valid JSON. The JSON must validate against this JSON Schema: "
            f"{json.dumps(output_schema.model_json_schema(), separators=(',', ':'))}"
        ),
    )
    completion = LiteLLMClient(settings).complete(
        [schema_instruction, *messages],
        model=model,
        temperature=temperature,
        response_format_json=True,
    )

    try:
        parsed = output_schema.model_validate_json(completion.content)
    except ValidationError as exc:
        raise StructuredOutputError("LLM output failed Pydantic validation.") from exc

    return StructuredOutputResult(parsed=parsed, completion=completion)


def _stub_structured_output(
    output_schema: type[StructuredModel],
    messages: Sequence[ChatMessage],
    model_name: str,
) -> StructuredOutputResult:
    subject = _last_user_message(messages)
    payload = {
        name: _fake_value(field.annotation, name=name, subject=subject)
        for name, field in output_schema.model_fields.items()
    }
    parsed = output_schema.model_validate(payload)
    content = parsed.model_dump_json()
    prompt_tokens = sum(len(message.content.split()) for message in messages)
    completion_tokens = len(content.split())
    completion = LLMCompletion(
        content=content,
        model_provider="stub",
        model_name=f"deterministic-dev-stub:{model_name}",
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=prompt_tokens + completion_tokens,
        total_cost=Decimal("0"),
        raw_response={"stub": True, "content": parsed.model_dump(mode="json")},
        used_stub=True,
    )
    return StructuredOutputResult(parsed=parsed, completion=completion)


def _last_user_message(messages: Sequence[ChatMessage]) -> str:
    for message in reversed(messages):
        if message.role == "user":
            return message.content
    return "the provided strategic idea"


def _fake_value(annotation: Any, *, name: str, subject: str) -> Any:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin in (UnionType, Union):
        non_null_args = [arg for arg in args if arg is not type(None)]
        return _fake_value(non_null_args[0], name=name, subject=subject) if non_null_args else None

    if origin is Literal:
        return args[0] if args else None

    if origin is list:
        inner = args[0] if args else str
        return [
            _fake_value(inner, name=_singularize(name), subject=subject),
            _fake_value(inner, name=f"secondary {_singularize(name)}", subject=subject),
        ]

    if origin is dict:
        return {}

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return {
            child_name: _fake_value(child.annotation, name=child_name, subject=subject)
            for child_name, child in annotation.model_fields.items()
        }

    if annotation is str:
        return _fake_string(name, subject)
    if annotation is int:
        return 1
    if annotation is float:
        return 0.5
    if annotation is bool:
        return False
    if annotation is Decimal:
        return Decimal("0.5")

    return None


def _fake_string(name: str, subject: str) -> str:
    readable = name.replace("_", " ")
    compact_subject = " ".join(subject.split())[:160]
    if "summary" in name:
        return f"Deterministic summary for: {compact_subject}"
    if "uncert" in name:
        return "Whether the target user has urgent enough pain to pay."
    if "next" in name or "step" in name:
        return "Add three evidence sources, then generate the first cited brief."
    if "user" in name:
        return "Early-stage founder"
    return f"{readable.capitalize()} generated by deterministic dev stub."


def _singularize(name: str) -> str:
    return name[:-1] if name.endswith("s") else name
