apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: thesys
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - workloads.yaml
  - services.yaml
  - network-policies.yaml
  - disruption-budgets.yaml
  - image-digest-policy.yaml
