apiVersion: v1
kind: ServiceAccount
metadata:
  name: thesys-api
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: thesys-worker
automountServiceAccountToken: false
